-- Tipos
create type order_status as enum ('created','awaiting_payment','paid','separating','shipped','delivered','canceled','refunded');
create type payment_method as enum ('pix','card','boleto');
create type payment_status as enum ('pending','approved','rejected','refunded','expired');

-- Perfis
create table public.profiles (
  id uuid primary key default auth.uid(),
  role text not null default 'customer' check (role in ('customer','admin','staff')),
  name text,
  phone text,
  created_at timestamptz not null default now()
);

-- Categorias
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  parent_id bigint references public.categories(id) on delete set null,
  position int not null default 0
);

-- Produtos
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description_md text,
  care_instructions_md text,
  category_id bigint not null, -- Corrigido de 'bick int' para 'bigint'
  weight_g int,
  dimensions_json jsonb,
  is_active boolean not null default true,
  foreign key (category_id) references public.categories(id) on delete restrict
);

-- Carrinhos
create table public.carts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete set null,
  session_id text,
  coupon_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Itens do carrinho
create table public.cart_items (
  id uuid primary key default gen_random_uuid(),
  cart_id uuid not null references public.carts(id) on delete cascade,
  variant_id bigint not null, -- Assumindo que 'variants' será criada ou é um placeholder
  quantity int not null check (quantity > 0),
  unit_price_snapshot numeric(12,2) not null
);

-- Pedidos
create table public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete set null,
  cart_id uuid references public.carts(id),
  status order_status not null default 'created',
  total_items numeric(12,2), -- Corrigido
  item_count int not null default 0, -- Corrigido
  starts_at timestamptz,
  ends_at timestamptz,
  scope text check (scope in ('all','category','product'))
);

-- Reviews (Adicionado)
create table public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  rating int not null check (rating >= 1 and rating <= 5),
  comment text,
  is_approved boolean not null default false,
  created_at timestamptz not null default now()
);

-- Índices úteis
create index cart_items_cart_idx on public.cart_items(cart_id);
-- create index order_items_order_idx on public.order_items(order_id); -- Comentado, pois 'order_items' não está no DDL fornecido

-- Habilitar Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.reviews enable row level security;

-- Políticas de RLS
-- profiles (self read/update)
create policy "Enable read access for own profile" on public.profiles for select using (auth.uid() = id);
create policy "Enable update access for own profile" on public.profiles for update using (auth.uid() = id);

-- orders (owner read)
create policy "Enable read access for order owner" on public.orders for select using (auth.uid() = user_id);

-- reviews (insert by authenticated; select only approved)
create policy "Enable insert for authenticated users" on public.reviews for insert with check (auth.role() = 'authenticated');
create policy "Enable select for approved reviews" on public.reviews for select using (is_approved = true);

-- Seeds de Categorias
insert into public.categories (name, slug, position) values
('Pijamas Femininos', 'pijamas-femininos', 1),
('Lingerie Sensual', 'lingerie-sensual', 2),
('Conjuntos Íntimos', 'conjuntos-intimos', 3),
('Robes e Camisolas', 'robes-camisolas', 4),
('Cuecas Masculinas', 'cuecas-masculinas', 5),
('Meias e Acessórios', 'meias-acessorios', 6),
('Linha Noiva', 'linha-noiva', 7),
('Fitness Íntimo', 'fitness-intimo', 8),
('Modeladores', 'modeladores', 9),
('Infantil', 'infantil', 10);

-- Seeds de Produtos (Pijamas/Lingerie)
-- Assumindo category_id 1 para Pijamas Femininos e 2 para Lingerie Sensual
insert into public.products (name, slug, description_md, care_instructions_md, category_id, is_active) values
('Pijama de Seda Luxo', 'pijama-seda-luxo', 'Pijama feminino de seda pura, toque macio e caimento perfeito.', 'Lavar à mão com água fria.', 1, true),
('Conjunto Renda Francesa', 'conjunto-renda-francesa', 'Lingerie sensual com detalhes em renda francesa e bojo estruturado.', 'Lavar à mão, não usar alvejante.', 2, true),
('Pijama Curto Verão', 'pijama-curto-verao', 'Pijama leve e fresco para as noites de verão, em algodão.', 'Pode ser lavado na máquina.', 1, true),
('Body Transparente', 'body-transparente', 'Body em tule transparente com bordados delicados, ideal para momentos especiais.', 'Lavar à mão, secar à sombra.', 2, true),
('Pijama Longo Inverno', 'pijama-longo-inverno', 'Pijama flanelado para o inverno, super quentinho e confortável.', 'Lavar na máquina em ciclo suave.', 1, true),
('Calcinha Fio Dental Renda', 'calcinha-fio-dental-renda', 'Calcinha fio dental em renda elástica, sem costura.', 'Lavar à mão.', 2, true),
('Pijama Infantil Unicórnio', 'pijama-infantil-unicornio', 'Pijama divertido de unicórnio para crianças, em malha de algodão.', 'Lavar na máquina.', 10, true),
('Sutiã Push-up Conforto', 'sutia-push-up-conforto', 'Sutiã com bojo push-up e aro, para máximo conforto e sustentação.', 'Lavar à mão.', 3, true),
('Robe de Cetim', 'robe-de-cetim', 'Robe elegante em cetim, perfeito para relaxar em casa.', 'Lavar à mão.', 4, true),
('Cueca Boxer Algodão', 'cueca-boxer-algodao', 'Kit com 3 cuecas boxer em algodão, toque macio e ajuste perfeito.', 'Lavar na máquina.', 5, true),
('Meia 7/8 Arrastão', 'meia-7-8-arrastao', 'Meia 7/8 arrastão com detalhes em renda, para um look ousado.', 'Lavar à mão.', 6, true),
('Conjunto Noiva Renda', 'conjunto-noiva-renda', 'Conjunto de lingerie especial para noivas, em renda e seda.', 'Lavar à mão.', 7, true);
