-- Tabela de Variações de Produto
create table public.variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  sku text not null unique,
  gtin text,
  color text not null,
  "size" text not null,
  price numeric(12, 2) not null,
  compare_at_price numeric(12, 2),
  stock int not null default 0,
  is_active boolean not null default true,
  constraint unique_variant unique (product_id, color, "size")
);

-- Tabela de Lista de Espera (Waitlist) para produtos fora de estoque
create table public.waitlist (
  id uuid primary key default gen_random_uuid(),
  variant_id bigint not null references public.variants(id) on delete cascade,
  email text not null,
  created_at timestamptz not null default now()
);

-- Adicionar comentários para referência
comment on table public.variants is 'Stores product variations like different sizes and colors.';
comment on table public.waitlist is 'Stores user subscriptions for out-of-stock product variants.';

-- Habilitar RLS na tabela de waitlist
alter table public.waitlist enable row level security;

-- Políticas de RLS para waitlist
-- Permitir que qualquer pessoa (mesmo não autenticada) se inscreva na lista de espera.
create policy "Enable insert for anyone" on public.waitlist for insert with check (true);

-- Ninguém pode ver os e-mails na lista de espera (apenas o admin com a service_role key).
create policy "Disallow select for everyone" on public.waitlist for select using (false);
