-- Tabela de Imagens de Produto
create table public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  url text not null,
  alt text,
  position int not null default 0,
  is_primary boolean not null default false
);

-- Adicionar um índice no product_id para buscas mais rápidas
create index idx_product_images_product_id on public.product_images(product_id);

-- Adicionar comentário para referência
comment on table public.product_images is 'Stores multiple images for each product.';
