-- Enum para tipo de cupom
create type coupon_type as enum ('percent', 'fixed', 'free_shipping');

-- Enum para escopo de cupom
create type coupon_scope as enum ('all', 'category', 'product');

-- Tabela de Cupons de Desconto
create table public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  type coupon_type not null,
  value numeric(10, 2) not null,
  min_subtotal numeric(10, 2) default 0,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  max_uses int,
  used_count int not null default 0,
  is_active boolean not null default true,
  -- O escopo pode ser expandido no futuro para aplicar a produtos/categorias específicas
  scope coupon_scope not null default 'all',
  created_at timestamptz not null default now()
);

-- Adicionar um índice no código do cupom para buscas rápidas
create index idx_coupons_code on public.coupons(code);

-- Adicionar comentário para referência
comment on table public.coupons is 'Stores discount coupons and their rules.';

-- Seed de cupons de exemplo
insert into public.coupons 
  (code, type, value, min_subtotal, is_active)
values
  ('BEMVINDO10', 'percent', 10, 50.00, true), -- 10% de desconto em compras acima de R$50
  ('20OFF', 'fixed', 20.00, 100.00, true), -- R$20 de desconto em compras acima de R$100
  ('FRETEGRATIS', 'free_shipping', 0, 150.00, true); -- Frete grátis acima de R$150
