-- Enum para o tipo de movimento de inventário
create type inventory_movement_type as enum (
  'reserve', -- Reserva de estoque durante o checkout
  'confirm', -- Confirmação da baixa de estoque após pagamento
  'cancel',  -- Retorno do estoque ao cancelar um pedido
  'adjust'   -- Ajuste manual de estoque
);

-- Tabela para rastrear movimentos de inventário
create table public.inventory_movements (
  id bigint generated by default as identity primary key,
  variant_id bigint not null references public.variants(id) on delete restrict,
  type inventory_movement_type not null,
  quantity int not null,
  order_id uuid references public.orders(id) on delete set null,
  reason text,
  created_at timestamptz not null default now()
);

-- Adicionar um índice no variant_id para buscas mais rápidas
create index idx_inventory_movements_variant_id on public.inventory_movements(variant_id);
create index idx_inventory_movements_order_id on public.inventory_movements(order_id);

-- Adicionar comentários para referência
comment on table public.inventory_movements is 'Tracks all movements for each product variant stock.';
comment on column public.inventory_movements.type is 'The type of inventory movement (e.g., reserve, confirm, cancel).';
comment on column public.inventory_movements.quantity is 'The amount of stock moved. Can be positive or negative.';
comment on column public.inventory_movements.order_id is 'The order associated with this stock movement, if any.';

-- Habilitar RLS
alter table public.inventory_movements enable row level security;

-- Políticas de RLS
-- Apenas o backend (com service_role) deve ter permissão para modificar o inventário.
create policy "Allow full access for service_role" on public.inventory_movements
  for all using (false); -- Ninguém pode ler por padrão
